package com.example.xty.helloagain.MyDataBase;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.xty.helloagain.MyDataBase.MyCurriculumTable;

import com.example.xty.helloagain.MyDataBase.MyCurriculumTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCurriculumTableDaoConfig;

    private final MyCurriculumTableDao myCurriculumTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCurriculumTableDaoConfig = daoConfigMap.get(MyCurriculumTableDao.class).clone();
        myCurriculumTableDaoConfig.initIdentityScope(type);

        myCurriculumTableDao = new MyCurriculumTableDao(myCurriculumTableDaoConfig, this);

        registerDao(MyCurriculumTable.class, myCurriculumTableDao);
    }
    
    public void clear() {
        myCurriculumTableDaoConfig.getIdentityScope().clear();
    }

    public MyCurriculumTableDao getMyCurriculumTableDao() {
        return myCurriculumTableDao;
    }

}
