package com.example.xty.helloagain.MyDataBase;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CLASSROOM_INFO".
*/
public class ClassroomInfoDao extends AbstractDao<ClassroomInfo, Long> {

    public static final String TABLENAME = "CLASSROOM_INFO";

    /**
     * Properties of entity ClassroomInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClassroomName = new Property(1, String.class, "classroomName", false, "classroomName");
        public final static Property ClassroomCapacity = new Property(2, String.class, "classroomCapacity", false, "classroomCapacity");
    };


    public ClassroomInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ClassroomInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSROOM_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"classroomName\" TEXT," + // 1: classroomName
                "\"classroomCapacity\" TEXT);"); // 2: classroomCapacity
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSROOM_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClassroomInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String classroomName = entity.getClassroomName();
        if (classroomName != null) {
            stmt.bindString(2, classroomName);
        }
 
        String classroomCapacity = entity.getClassroomCapacity();
        if (classroomCapacity != null) {
            stmt.bindString(3, classroomCapacity);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClassroomInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String classroomName = entity.getClassroomName();
        if (classroomName != null) {
            stmt.bindString(2, classroomName);
        }
 
        String classroomCapacity = entity.getClassroomCapacity();
        if (classroomCapacity != null) {
            stmt.bindString(3, classroomCapacity);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ClassroomInfo readEntity(Cursor cursor, int offset) {
        ClassroomInfo entity = new ClassroomInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // classroomName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // classroomCapacity
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClassroomInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClassroomName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setClassroomCapacity(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClassroomInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClassroomInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
