package com.example.xty.helloagain.MyDataBase;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        MyCurriculumTableDao.createTable(db, ifNotExists);
        SettingsDao.createTable(db, ifNotExists);
        HolidaysDao.createTable(db, ifNotExists);
        MondayTableDao.createTable(db, ifNotExists);
        FridayTableDao.createTable(db, ifNotExists);
        SaturdayTableDao.createTable(db, ifNotExists);
        SundayTableDao.createTable(db, ifNotExists);
        ThursdayTableDao.createTable(db, ifNotExists);
        TuesdayTableDao.createTable(db, ifNotExists);
        WednesdayTableDao.createTable(db, ifNotExists);
        CourseInfoDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        MyCurriculumTableDao.dropTable(db, ifExists);
        SettingsDao.dropTable(db, ifExists);
        HolidaysDao.dropTable(db, ifExists);
        MondayTableDao.dropTable(db, ifExists);
        FridayTableDao.dropTable(db, ifExists);
        SaturdayTableDao.dropTable(db, ifExists);
        SundayTableDao.dropTable(db, ifExists);
        ThursdayTableDao.dropTable(db, ifExists);
        TuesdayTableDao.dropTable(db, ifExists);
        WednesdayTableDao.dropTable(db, ifExists);
        CourseInfoDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(MyCurriculumTableDao.class);
        registerDaoClass(SettingsDao.class);
        registerDaoClass(HolidaysDao.class);
        registerDaoClass(MondayTableDao.class);
        registerDaoClass(FridayTableDao.class);
        registerDaoClass(SaturdayTableDao.class);
        registerDaoClass(SundayTableDao.class);
        registerDaoClass(ThursdayTableDao.class);
        registerDaoClass(TuesdayTableDao.class);
        registerDaoClass(WednesdayTableDao.class);
        registerDaoClass(CourseInfoDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
